# Generated by Django 4.2.3 on 2023-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cocking_time',
            new_name='cooking_time',
        ),
    ]
