version: '3.3'
volumes:
  pg_data:
  frontend_static:
  backend_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: kuzenkov/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: kuzenkov/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - frontend_static:/static

  gateway:
    image: kuzenkov/foodgram_gateway:latest
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - media:/media
      - frontend_static:/usr/share/nginx/html/
      - backend_static:/usr/share/nginx/html/static_backend