# Generated by Django 4.2.3 on 2023-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.BooleanField(blank=True, default=False, help_text='Заблокированные пользователи не могут использовать сайт.', null=True, verbose_name='Блокировка пользователя'),
        ),
    ]
